"""decisions table

Revision ID: 92a9c98fd8f6
Revises: ea5a86f32659
Create Date: 2023-11-06 20:56:06.538730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a9c98fd8f6'
down_revision = 'ea5a86f32659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('what', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('when', sa.Date(), nullable=True),
    sa.Column('impulsive', sa.String(length=3), nullable=True),
    sa.Column('confident', sa.String(length=3), nullable=True),
    sa.Column('confidence_scale', sa.Integer(), nullable=True),
    sa.Column('backup', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_timestamp'))

    op.drop_table('decisions')
    # ### end Alembic commands ###
